apiVersion: v1
kind: Service
metadata:
  name: jw-workshop-svc
  labels:
    app: jw-workshop-node
spec:
  ports:
    - name: express-server
      protocol: TCP
      port: 8080
      nodePort: 30480
  selector:
    app: jw-workshop-node
  type: NodePort
